### ISSUE TITLE
add a nav at the top and add scrollspy

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashlesssociety.github.io#11]

**Comment by utunga** [comment]
What I need to do is maybe name the sections for nav bar.. i will put them here

**Comment by utunga** [comment]
I added the following nav to IndexNavBar.js
THE APP
WHY
CASHLESS CREDIT
GOVERNANCE
GET INVOLVED

It sort of 'works' but
- it doesn't track the currently scrolled item correctly
- the transitions are a bit abrupt (no 'scroll to' animation)
- probably the left most link aka the logo should take you back to top of page. 

Happy to consider changes in wording for space etc but that's what I came up for.

**Comment by karenkun** [comment]
@utunga I added the scrollspy component to the nav, but its still not working right...  Maybe you can figure it out? 
This is the branch: [#11_add_scrollspy_to_nav](https://github.com/CashlessSociety/cashlesssociety.github.io/commit/4fddf9317030f8d4dcc6289c59bf82cbe74f9528)

This is the library: https://github.com/keidrun/reactstrap-scrollspy
