### ISSUE TITLE
Regarding vertical timeline / arrows for the steps involved 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashlesssociety.github.io#5]
Was playing around with this a bit yesterday while in the middle of hours long zoom calls. 

Realize that this doesn't have to be a perfect logical map but I would like to somehow try to communicate the idea that it can sort of go in two directions - either reciprocate *or* pay from reserves. 

I had a play with different orders of things and with different places for it to diverge and I thought maybe it would make snese if we could do something like this 

```

  Send 
   |
   v
Reciprocate
   |     |
   v.    |
 Vest    |
   |     |
   v.    |
  Pay    |
   |     |
   v.    v
  Demurrage 
  
 ```

What do you think? @karenkun any way we could do something like this ? 

Am starting yet another hours long zoom meeting now "strategic planning, yay!" but I may try to have a play with this today if i can - text content wise.

**Comment by utunga** [comment]
```
send <--+
          |
 |       |
 |       |
 |       |
 v       |

reciprocate

 |       |
 |       |
 |       |
 v       |
          |
vest    |
          |
 |       |
 |       |
 |       |
 v       v

 demurrage
```

And we could merge 'vest' and 'payment' into one explanation.. but I guess I'm over thinking it ?

**Comment by utunga** [comment]
Been working on phrasing a bit. Pasting content into anyword.com, getting 'suggestions', editing it a bit then pasting it again. 

Thought I'd make a note of current phrasing - putting this in this issue so we can discuss. But I can also, of course, make these changes directly in the web app. 

This is the 'four steps' version per this diagram but we could, of course, split 'vest' and 'spend' into two steps.

  ```
send <--+
          |
 |       |
 |       |
 |       |
 v       |

reciprocate

 |       |
 |       |
 |       |
 v       |
          |
vest    |
          |
 |       |
 |       |
 |       |
 v       v

 demurrage
```

**Send** 

Send anyone money in the form of a cashless credit. A credit is a signed, irrevocable ‘promise to pay it forward’ backed by your reserves and reputation. Send a credit as payment or acknowledgement of work done for you by others.

**Reciprocity** 

The simplest way to erase your cashless credits is offering back an equal value of your time in exchange. For example, if a graphic designer helped you design a logo and you helped with some of their work in turn you have found a ‘reciprocity’ loop that erases the debt. But you don't have to find an exact swap. The Cashless AI works hard at finding and suggesting trades that will help you erase your outstanding debits or spend your credits.

**Vest and spend**

From day one through month two, the hard currency reserves build up in value, rewarding the recipient for holding on to your promise token. Like all living systems, cashless promises go through a natural birth, growth and decay cycle. As they vest, promises are like trees bearing fruit in the form of hard currency reserves, which can be ‘picked’ (swapped into the receiver's wallet) at any moment.

**Demurrage** 

Unlike the inexorable growth imperative of traditional debt, or the speculation incentives on most blockchains, cashless credits live in balance with nature, start to depreciate back to zero a few months after reaching their highest value. We believe that credit should serve the community, not the other way around. Cashless credits ‘want’ to be spent. This encourages your local community, local relationships, and local engagement.

**Comment by karenkun** [comment]
Yeah I'll add the arrows for the "alternate routes".
